repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.16.0
  hooks:
      - id: commitlint
        stages: [commit-msg]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
      - id: markdownlint
        stages: [pre-commit]

- repo: https://github.com/Calinou/pre-commit-luacheck
  rev: v1.0.0
  hooks:
      - id: luacheck
        stages: [pre-commit]
